### ISSUE TITLE
Creation of macros for the "NetHackScore-v0" environment

### ISSUE THREAD

**Issue by JoshMakesCode** [facebookresearch/nle#105]
If I were to try and create a macro for eating items in the agent's inventory in the gym environment, how would I go about doing so? More specifically, how can I select options in the game without stepping the environment which is currently causing issues? For example, when prompted with the following message:

`What do you want to eat? [fghi or ?*]`

How do I select an option such as `f` without stepping in the environment since trying to pass `f` or `ord(f)` gives an index out or range error.

Any help would be highly appreciated.

**Comment by heiner** [comment]
Hey Josh,

Thanks for your interest in NLE. This is a great question! We are trying to figure out how to deal with item handling ourselves at the moment.

The reason `ord('f')` gives you an index error is that on the gym environment level, NLE maintains an "action set" and expects indices into that list. This means if you enable `Command.FIRE` as an action (i.e., put it into the action set), its index will give the underlying game a `ord('f')` action which would eat item `f` given the prompt you show.

This gets more tricky for e.g. items with character `S` as this would require enabling the `SAVE` action...

We could change how this works, but we'd have to stay within NetHack's core logic nevertheless. Currently, the parts of NLE we added on top of upstream NetHack don't necessarily "understand" what NetHack is doing at the moment, they just extract and expose some game state.

How to properly deal with this "changing action mappings" situation is a research question of sorts.

**Comment by yobibyte** [comment]
To add to @heiner's comment, you can get the mapping from indices to action semantics by calling ```env.print_action_meanings()``` [method](https://github.com/facebookresearch/nle/blob/a7de0d0326bc962dba50d6822e06e4d129d8a7d4/nle/env/base.py#L287). 

However, the semantics does not necessarily hold. For instance, pressing `e` after pressing `e` will select an inventory item in the corresponding slot.

**Comment by JoshMakesCode** [comment]
Thank you for the fast reply.

Does that mean that the gym environment only allows the agent to eat food that it is currently standing over? The paper on the environment is a bit ambiguous about this matter. But also considering that even calling the `EAT` command when standing over something such as a corpse presents you with the option to reply yes or no to eating the item on the ground, how does the agent environment handle this?

**Comment by heiner** [comment]
Hey Josh,

The environment allows the agent to do whatever a human can do provided the relevant action is in the action set. That is, if the hero stands on a square with food and the player presses `e`, the game will first ask if the food on that square should be eaten. If not, it will prompt for edible items from the inventory, if any. The logic there is NetHack's, not ours, and we didn't (and don't plan to) change it. However, to eat an item with e.g. letter `f`, the action corresponding to `ord('f')` needs to be enabled (aka be in the action set). That poses some trickiness for ML approaches in that actions are very context-dependent. How to deal with this is a question of ongoing research.

**Comment by adyomin** [comment]
Is there a part of the observation object that a) indicates that the game is in the dialogue/context dependent menu mode and b) provides details of the options?

**Comment by heiner** [comment]
Closing for now. Please reopen if still relevant.
