### ISSUE TITLE
How do I change the adventurer's class using the NLE api?

### ISSUE THREAD

**Issue by justinglibert** [facebookresearch/nle#106]
## 🚀 Feature

I didn't find how to change the adventurer class using the NLE api, only its name (using the `character` kwarg of any NLE environment)

**Comment by rockt** [comment]
Hi @justinglibert,

Thanks for you interest in NLE. You can change the class using the character argument (https://github.com/facebookresearch/nle/blob/master/nle/env/base.py#L96). The format is as follows:
AAA-BBB-CCC-DDD where
AAA: first three letters of the role (e.g. mon is monk, wiz is wizard etc.)
BBB: first three letters of the race (e.g. hum is human)
CCC: first three letters of the alignment (law, neu, cha)
DDD: first three letters of the gender (mal/fem)

Cheers,
Tim

**Comment by rockt** [comment]
By the way, for more details on role, race and alignment, see https://nethackwiki.com/wiki/Player#Role.2C_race_and_alignment

**Comment by heiner** [comment]
Unfortunately this approach fails to work if you use wizard mode, in which case one has to do the same with the `role:` etc options.
