### ISSUE TITLE
Reproducing the paper's results

### ISSUE THREAD

**Issue by ludns** [facebookresearch/nle#107]
## 🚀 Feature
I understand that sharing the paper's code is a lot of work, but could just share your torchbeast config? I have a really hard time reproducing your results, even with a distributed setting. The hyperparameters were not included in the paper, and it will help reproducibility if you share them. Thanks :smile: 
As an example, I only reach 120 mean score (over the last 100 episodes) on the score task after 1B steps with 32 actors running in a distributed setting, which is far off the ~800 reported in the paper with the default class (and the CNN baseline found in the demo agent in `nle/nle/agent.py`)

**Comment by aleSuglia** [comment]
@justinglibert as reported in the issue https://github.com/facebookresearch/nle/issues/90, the full code release will happen very soon. Let's patiently wait :)

**Comment by heiner** [comment]
Hey Justin,

Thanks again for your continued interest in NLE and for this question. We will definitely release this code, and the fact that a number of people are asking is currently making us re-asses if we should perhaps do this before we rewrite it for readability and usability (the current codebase is not much fun to use).

I hope Alessandro is correct in saying "very soon" but I don't quite want to commit to that language myself :). But stay tuned.

**Comment by justinglibert** [comment]
Hey Heinrich,
Thanks for coming back to me! I understand the code cannot be released right now, and I am looking forward to a release soon.

Do you still think it is not possible to share the hyperparams that you have used here, in this issue? We all know it will not be enough for a complete reproduction, but it will help me (and probably others) understand why a normal IMPALA setup only reaches 1/8th of the reported results after the same number of steps processed. Hopefully it is something you and your team can do without much work.

**Comment by heiner** [comment]
Hey Justin,

That's a fair question.

As you know we are not using this MonoBeast-style `agent.py` for our paper results but something based on a bastardized version of PolyBeast. This makes for a very high-dimensional space with lots of choices that need to be gotten just right in order to get our results (in fact, when we changed the environment itself slightly before we released it it perturbated our results a bit as well ...).

We report on the relevant hyperparameters in the appendix of the paper, but here's the flags we use for (one of) our actual experiments.

```python
experiment_args = dict(
        alpha=0.99,
        baseline_cost=0.5,
        batch_size=32,
        character=[
            "mon-hum-neu-mal",
            "val-dwa-law-fem",
            "wiz-elf-cha-mal",
            "tou-hum-neu-fem",
        ],
        crop_dim=9,
        disable_cuda=False,
        discounting=0.999,
        embedding_dim=32,
        entropy_cost=0.001,
        env=["score", "gold", "eat", "staircase", "pet", "explore", "oracle"],
        # env=["score", "staircase"],
        epsilon=1.0e-06,
        fn_penalty_step="constant",
        grad_norm_clipping=40,
        hidden_dim=128,
        layers=5,
        learning_rate=0.0002,
        max_learner_queue_size=None,
        max_num_steps=1e9,
        max_num_ttyrec=None,
        model=["cnn"],
        num_actors=64,
        num_inference_threads=1,
        num_learner_threads=1,
        num_seeds=0,
        # optimizer="rmsprop",
        penalty_step=-0.001,
        penalty_time=0.0,
        pipes_basename="unix:/tmp/polybeast",
        relative_reward=False,
        reward_clipping="tim",
        reward_lose=0,
        reward_win=100,
        single_ttyrec=False,
        start_servers=True,
        total_steps=[1e9],
        unroll_length=[80],
        use_lstm=True,
        use_index_select=[True],
    )
```

We also set

```python
args["num_inference_threads"] = args["num_learner_threads"]
args["max_learner_queue_size"] = args["batch_size"]
```

The model is as we describe it in the paper; I believe the model in `agent.py` is very similar. We've since worked on this a bit and get slightly better results than reported in the paper by doing a few model tweaks. We've discussed moving forward the code release (and releasing a less clean version) today, so stay tuned.

**Comment by justinglibert** [comment]
Great! Thanks Heinrich!
I'll see if using those params help.

**Comment by justinglibert** [comment]
What does `reward_clipping="tim"` mean? In the agent.py it uses a simple clamp. What about `tim`?

**Comment by aleSuglia** [comment]
@justinglibert I had the same doubt but I guess it's part of the tricks implemented in their improved version :)

**Comment by heiner** [comment]
We tried various clipping mechanisms. E.g.

```python
def clip(flags, rewards):
    if flags.reward_clipping == "tim":
        clipped_rewards = torch.tanh(rewards / 100.0)
    elif flags.reward_clipping == "soft_asymmetric":
        squeezed = torch.tanh(rewards / 5.0)
        # Negative rewards are given less weight than positive rewards.
        clipped_rewards = torch.where(rewards < 0, 0.3 * squeezed, squeezed) * 5.0
    elif flags.reward_clipping == "none":
        clipped_rewards = rewards
    else:
        raise NotImplementedError("reward_clipping=%s" % flags.reward_clipping)
    return clipped_rewards
```

**Comment by condnsdmatters** [comment]
For anyone still looking to reproduce results, I suggest looking at the `neurips2020release` branch.
