### ISSUE TITLE
Cannot moport Blstats from nle.fbs

### ISSUE THREAD

**Issue by jrieffel** [facebookresearch/nle#11]
## 🐛 Bug

I've made progress in installing nle, but hit some snags (most resolved by telling the nle environment's conda to pip install gym and zmq). However now I'm getting the error below:

ImportError: cannot import name 'Blstats' from 'nle.fbs' (unknown location)

## To Reproduce

Python 3.7.7 (default, Mar 26 2020, 15:48:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym
>>> import nle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rieffelj/src/nle/nle/__init__.py", line 4, in <module>
    import nle.env
  File "/home/rieffelj/src/nle/nle/env/__init__.py", line 4, in <module>
    from nle.env.base import NLE, DUNGEON_SHAPE, seed_list_to_dict
  File "/home/rieffelj/src/nle/nle/env/base.py", line 16, in <module>
    from nle import nethack
  File "/home/rieffelj/src/nle/nle/nethack/__init__.py", line 3, in <module>
    from nle.nethack.nethack import NetHack, SEED_KEYS
  File "/home/rieffelj/src/nle/nle/nethack/nethack.py", line 19, in <module>
    from nle.fbs import (  # noqa: F401
ImportError: cannot import name 'Blstats' from 'nle.fbs' (unknown location)

## Expected behavior

expected to run demo

## Environment

NLE version: N/A
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro K1200
Nvidia driver version: 384.130
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.3.1
[pip3] torchvision==0.4.2
[conda] Could not collect

**Comment by edran** [comment]
It looks like the repo is in your pypath. What happens after you do `pip install -e .`?

**Comment by edran** [comment]
Hey @jrieffel, just checking -- did you manage to get it to run?

**Comment by jrieffel** [comment]
Switched over to the docker...

**Comment by edran** [comment]
Sure, no worries! What's important is that you can use `nle` now :)

I'll close this issue.
