### ISSUE TITLE
Using NLE on Google Colab

### ISSUE THREAD

**Issue by Mayur28** [facebookresearch/nle#117]
Hi!

I just wanted to find you if anyone has any guidance on how to run Nethack on Google Colab please. I've attempted to do so but I continuously encounter the following error:

`Building wheels for collected packages: nle, pybind11
  Building wheel for nle (PEP 517) ... error
  ERROR: Failed building wheel for nle
  Running setup.py clean for nle
  Building wheel for pybind11 (PEP 517) ... done
  Created wheel for pybind11: filename=pybind11-2.6.0-cp36-none-any.whl size=187422 sha256=19f0174f3752e665a854e4cc518d3520a004ae314c9b74ee7ba75c8040aaf0b0
  Stored in directory: /root/.cache/pip/wheels/12/76/9f/16466fd46ea286eb3b8724b77e6088c33388d42248aa1372c7
Successfully built pybind11
Failed to build nle
ERROR: Could not build wheels for nle which use PEP 517 and cannot be installed directly`

Any help will be highly appreciated.

**Comment by heiner** [comment]
Hey Mayur28,

Thanks for your interest in NLE!

The error message `Failed to build nle ERROR: Could not build wheels for nle which use PEP 517 and cannot be installed directly` can mean lots of things. I suspect it's a compilation error due to missing dependencies (e.g., flex/bison, libbz2-dev, libncurses-dev). Typically there's a longer error message that gives more details, could you see if you can get that in this case?

**Comment by Mayur28** [comment]
Hi Heiner!

Thanks for getting back to me.

Over the past 3 weeks, I've tried numerous options in attempt to get the NLE environment to work on Google Collab to no avail. This includes even trying to setup a conda environment (as recommended in the README), however, this did not resolve the issue. The installation overall seems successful (judging from the terminal output), even when I install the packages mentioned in the README, but I get the following error once the `pip install nle` command is reached and when I create a conda environment:
~~~
``` Building wheels for collected packages: nle, gym, future\
  Running setup.py bdist_wheel for nle ... error\
  Failed building wheel for nle\
  Running setup.py clean for nle  
  Running setup.py bdist_wheel for gym ... done  
  Stored in directory: /root/.cache/pip/wheels/05/31/54/501ff9f64e6084bbcb75e600f257f3c628b19f0eaadc37162d  
  Running setup.py bdist_wheel for future ... done  
  Stored in directory: /root/.cache/pip/wheels/8b/99/a0/81daf51dcd359a9377b110a8a886b3895921802d2fc1b2397e  
Successfully built gym future  
Failed to build nle  
Installing collected packages: pybind11, numpy, future, pyglet, cloudpickle, gym, nle  
  Found existing installation: numpy 1.14.0  
    Uninstalling numpy-1.14.0:  
      Successfully uninstalled numpy-1.14.0  
  Found existing installation: cloudpickle 0.5.2  
    Uninstalling cloudpickle-0.5.2:  
      Successfully uninstalled cloudpickle-0.5.2  
  Running setup.py install for nle ... error  
Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-a20pvk4_/nle/setup.py';  f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-fojpl_gv-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-a20pvk4_/nle/   ```  
~~~

Without creating a conda environment, I get the following error:
~~~
```Collecting nle
  Downloading https://files.pythonhosted.org/packages/70/6c/412567cf66bd4a9009ff8fdc077b2b71f1e660f16d2c06c68921fd0dbe48/nle-0.5.2.tar.gz (6.7MB)
     |████████████████████████████████| 6.7MB 8.6MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy>=1.16 in /usr/local/lib/python3.6/dist-packages (from nle) (1.18.5)
Collecting pybind11>=2.2
  Using cached https://files.pythonhosted.org/packages/92/a5/796ccb611a92cbdf1f6eaa9b2ec9458d5784a7b909efdf8e8afaa3861783/pybind11-2.6.0-py2.py3-none-any.whl
Requirement already satisfied: gym>=0.15 in /usr/local/lib/python3.6/dist-packages (from nle) (0.17.3)
Requirement already satisfied: cloudpickle<1.7.0,>=1.2.0 in /usr/local/lib/python3.6/dist-packages (from gym>=0.15->nle) (1.3.0)
Requirement already satisfied: pyglet<=1.5.0,>=1.4.0 in /usr/local/lib/python3.6/dist-packages (from gym>=0.15->nle) (1.5.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from gym>=0.15->nle) (1.4.1)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from pyglet<=1.5.0,>=1.4.0->gym>=0.15->nle) (0.16.0)
Building wheels for collected packages: nle
  Building wheel for nle (PEP 517) ... error
  ERROR: Failed building wheel for nle
  Running setup.py clean for nle
Failed to build nle
ERROR: Could not build wheels for nle which use PEP 517 and cannot be installed directly```
~~~

Any assistance would be highly appreciated.

**Comment by heiner** [comment]
There's something going on in the ellipsis in `Running setup.py bdist_wheel for nle ... error` and it would be good to get access to that. Perhaps there's some log file you could read?

Otherwise, doesn't colab allow you to run terminal commands too? Try those (inside the NLE directory; download if necessary):

```
mkdir build
cd build
cmake ..
make
```

If this produces lots of outputs, good. Copy and paste it all in here.

**Comment by Mayur28** [comment]
Hi Heiner,

I've managed to resolve the issue once I had generated a logfile. The issue was caused by an issue with cmake on Collab's side. Thank you for the assistance!

**Comment by heiner** [comment]
Hey Mayur28,

That's awesome.

Could you, for posterity, perhaps briefly describe the issue and how you fixed it? That might help others who run into the same problem when then start googling 👍 

Thanks

Heiner

**Comment by Mayur28** [comment]
Sure! For some reason, Collab refused to update cmake to a newer version (just stayed at 3.12 while the logfile revealed that 3.14 or higher is required). I then manually updated cmake via a binary distribution from their website which resolved the issue.
