### ISSUE TITLE
Allow reward function to consider action taken

### ISSUE THREAD

**Issue by RobertKirk** [facebookresearch/nle#155]
## 🚀  Feature: Allow reward function to consider action taken

It would be great if `_reward_fn` could take in the action taken, as well as the previous and current observation. This would enable users to define custom reward functions that take actions, which is common in RL literature. The context in which `_reward_fn` is called (`env.step(action)`) has this action in scope.

I think it would be relatively straightforward to implement by changing a few lines in `nle/env/base.py` and `nle/env/tasks.py`.

**Comment by heiner** [comment]
Hey Robert,

Thanks for your interest in NLE! Sorry for the late response, I was on leave for a bit.

Would you be willing to send us a PR with the proposed change?

**Comment by RobertKirk** [comment]
Sure, here it is: https://github.com/facebookresearch/nle/pull/166
