### ISSUE TITLE
crash "undefined symbol: has_colors"

### ISSUE THREAD

**Issue by cerisara** [facebookresearch/nle#157]
## 🐛 Bug

Crash when running any NLE script with error "undefined symbol: has_colors"

## To Reproduce

1. Install NLE through conda and "pip install nle"
2. run "python -m nle.scripts.play"

Output:

```
Available actions: (<MiscAction.MORE: 13>, <CompassDirection.N: 107>, <CompassDirection.E: 108>, <CompassDirection.S: 106>, <CompassDirection.W: 104>, <CompassDirection.NE: 117>, <CompassDirection.SE: 110>, <CompassDirection.SW: 98>, <CompassDirection.NW: 121>, <CompassDirectionLonger.N: 75>, <CompassDirectionLonger.E: 76>, <CompassDirectionLonger.S: 74>, <CompassDirectionLonger.W: 72>, <CompassDirectionLonger.NE: 85>, <CompassDirectionLonger.SE: 78>, <CompassDirectionLonger.SW: 66>, <CompassDirectionLonger.NW: 89>, <MiscDirection.UP: 60>, <MiscDirection.DOWN: 62>, <MiscDirection.WAIT: 46>, <Command.KICK: 4>, <Command.EAT: 101>, <Command.SEARCH: 115>)
/tmp/nleoo4f38qj/libnethack.so: undefined symbol: has_colors
```

## Expected behavior

no crash

## Environment

The collect script is working fine and gives:

NLE version: 0.6.0
PyTorch version: 1.8.1+cu102
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Red Hat Enterprise Linux release 8.1 (Ootpa)
GCC version: (GCC) 8.3.1 20190507 (Red Hat 8.3.1-4)
CMake version: Could not collect

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] numpysane==0.34
[pip3] torch==1.8.1
[conda] torch                     1.8.1                    pypi_0    pypi

## Additional context

There's no CUDA because I'm launching the script from the French Jean Zay cluster frontend, but the issue is the same from the compute nodes. I don't have admin rights.

**Comment by heiner** [comment]
Can you give me the output of `uname -a` on this machine?

**Comment by cerisara** [comment]
Linux jean-zay1 4.18.0-147.48.1.el8_1.x86_64 #1 SMP Wed May 12 08:42:42 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by heiner** [comment]
Thanks!

Could you try if installing the version from this branch fixes the issue:

```
pip install git+https://github.com/facebookresearch/nle.git@heiner/fixes
```

**Comment by cerisara** [comment]
It works !
Great ! How did you do that ?
Thanks a lot !

**Comment by cerisara** [comment]
I think I see, that's the test method that may not be defined; not sure why it's defined sometimes and sometimes not though... Not sure also whether not doing the test may impact other architectures, or if the test is really required (?)

**Comment by heiner** [comment]
NLE is a bit different from standard NetHack in that regard. We don't need to actually check what the terminal supports, we just produce tty output in one specific way.

**Comment by heiner** [comment]
It's merged now. You can install the latest version via

```
pip install git+https://github.com/facebookresearch/nle.git@master
```

but we'll also deploy this as version 0.6.1.

**Comment by cerisara** [comment]
Thank you very much !
