### ISSUE TITLE
Script to visualize saved agent play

### ISSUE THREAD

**Issue by dmadeka** [facebookresearch/nle#183]
Hi there,

Is there an easy way to visualize the games played by an agent - or trigger a saved agent to do forward passes and watch it play?

Thanks,

Dhruv

**Comment by KarolisRam** [comment]
Create the env like this to save replays:
`env = gym.make('NetHackChallenge-v0', savedir='replays')`
And then use this to play them:
`nle-ttyplay "nle.7444.0.ttyrec.bz2" -s 0.01`
-s is the speed.
You can also use some external tools to play and step through the replay, I personally use [jettyplay](http://nethack4.org/projects/jettyplay/).

**Comment by heiner** [comment]
Hey Dhruv,

Thanks for your interest in NLE.

As Karolis says, `nle-ttyplay` is on option in this case. It has keyboard commands that are not very well documented, but if you peek at its source code at https://github.com/facebookresearch/nle/blob/master/nle/scripts/ttyplay.py#L66 you can see it supports some kind of vi-style navigation as well as `+` and `-` to change the speed while it's running. There's also `nle-ttyplay2` which attempts to show which NetHack action was executed at a given time (the `ttyrec.bz2` files NLE writes are "ttyplay2" files, meaning they have an input channel as well as an output. Jettyplay can play these files too, as can the original [ttyplay2](https://github.com/Noeda/ttyrec2).
