### ISSUE TITLE
questions about action: kick and eat

### ISSUE THREAD

**Issue by CrazySssst** [facebookresearch/nle#190]
Hi, I am trying to train my agent  on the suite of tasks provided in your NIPS paper.  I noticed there are 23 available actions including 'movement',  'more', 'wait', 'search',  'kick' and 'eat'.  

I found that an agent must choose a direction after pressing the "kick" button. This is very strange and I have never seen a two-step action in Atari, MoJuCo and SMAC. Why not provide actions such as 'kick-to-left' ? 

In addition, ‘eat’ is also a 2-step action, the agent needs to choose what to eat from the backpack.

In my opinion, the 2-step actions hinder training. How do you deal with 2-step actions when you are training the agent? Hope to get your suggestions, thank you

**Comment by rockt** [comment]
Hi @CrazySssst, thanks for your question! I believe factorizing the action space the way we do makes sense as you would otherwise end up with a humongous action space--for example you would have a different eat, drop, throw, wear etc action for every item in the backpack. It's even works for spell casting and zapping wands, as you need to select the spell/wand from a menu and then a direction.  Exploring a large action space is known to be difficult, so this would most likely hinder training more than it helps. That said, feel free to play with training macro actions and let us know how it works :)

**Comment by heiner** [comment]
Hey @CrazySssst,

Thanks for your interest in NLE!

You're right that 2-step actions make training harder. If you are looking for a simpler environment, the environments you mention (Atari, etc) are more appropriate. The reason we put forward NetHack as a new frontier of RL research is precisely the complexities it introduces. Our hope is that the community can make progress on NetHack and thereby find methods that deal with these (almost "real-world") complexities.

**Comment by CrazySssst** [comment]
Thanks for your replies @rockt @heiner .
I am trying to modify the action space, such as adding 'kick to left' and 'auto-y' for 'eat' action and I will report my training results later.

Here is some suggests.
I know NLE  is complexities and is hoped to be a new frontier of RL research.  But I think simplifying the action space on small tasks (Eat,Gold, etc) will help attract researchers’ attention.  An overly complex environment can be prohibitive.

In addition, compared to 2-step actions, functional actions are easier to accept, just like alphaStar does.  What I mean is that the agent selects the type of action and the parameters of the action at the same time, then feed them into environments. 

For Eat tasks, It may be a better setting to prohibit choosing food from the backpack to eat, because the agent is not allowed to pick up food into the backpack. 

By the way, I noticed that your agent does not consider message information. Has it finally learned 2-step actions? For example, choosing the right direction when kicking. If the agent learns how to use 2-step action, can you tell me why?

Finally, thanks for your great work

**Comment by heiner** [comment]
Somewhat relevant: https://github.com/facebookresearch/nle/issues/230#issuecomment-891041979

> Notice that the game does not guarantee that you can eat/fire/etc in all situations. E.g., when polymorphed into a non-eating monster (cf. https://github.com/facebookresearch/nle/blob/master/src/eat.c#L2480). In other situations, the game might ask you additional questions (really eat the food in this tin, do you want to continue, etc). Coming up with an encapsulation of all this logic in general is going to be tricky.
