### ISSUE TITLE
Running multiple NLE environments results in episodes ending due to Trickery.

### ISSUE THREAD

**Issue by KarolisRam** [facebookresearch/nle#193]
## 🐛 Bug

Running multiple instances of NLE creates interference between them which results in episodes ending due to [Trickery](https://nethackwiki.com/wiki/Trickery).
It displays the following messages in the affected ttyrec:
`Cannot open file "1lock.13" for level 13 (errno2).--More--`
`Probably someone removed it.`
`You were tricked in The Dungeons of Doom ...`

## To Reproduce

1. Clone the [competition baselines](https://gitlab.aicrowd.com/eric_hammy/neurips-2021-the-nethack-challenge/tree/submission-baseline-0.5B)
2. Change line 8 in envs/wrappers.py to: `return aicrowd_gym.make("NetHackChallenge-v0", savedir='')` to save the replays
3. `python test_submission.py`

## Expected behavior

Episodes not ending due to Trickery.

## Environment

NLE version: 0.7.2
PyTorch version: 1.8.1+cu102
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.20.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 440.64.00
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.4

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.7.1
[pip3] numpy==1.20.3
[pip3] numpysane==0.33
[pip3] torch==1.8.1
[conda] Could not collect

## Additional context

I ran 127k episodes using 4 instances of the baselines, which run 32 NLE environments each. 8.8k (6.9%) ended due to Trickery.  
Then I ran 1k episodes using just a single instance, which runs 32 NLE environments. 63 (6.3%) ended due to Trickery.  
Lastly I changed NUM_ENVIRONMENTS to 1 and ran ~400 episodes that way, no Trickery observed.
Here's an example replay: [nle.4989.574.ttyrec.zip](https://github.com/facebookresearch/nle/files/6754336/nle.4989.574.ttyrec.zip)

**Comment by heiner** [comment]
Hey Karolis,

Thanks for this report, and thanks for your continued support of the NLE project!

We finally got around addressing this issue. If you `pip install` from the master branch, e.g. via

```
pip install git+https://github.com/facebookresearch/nle.git@master
```

the issue should be fixed? (I hope!)

Let us know if it isn't, or if you moved on from dealing with this.

Thanks.

**Comment by KarolisRam** [comment]
12k episodes using 4 instances * 32 NLE envs each - zero Trickery observed. Nice one, thank you!

**Comment by heiner** [comment]
That's awesome, thanks for checking!
