### ISSUE TITLE
[Challenge] Polyhydra libtorch Undefined Symbol Error

### ISSUE THREAD

**Issue by drothermel** [facebookresearch/nle#203]
See original issue on the aicrowd site: https://gitlab.aicrowd.com/nethack/neurips-2021-the-nethack-challenge/-/issues/16

Tried to run baselines with polyhyrda but are getting an undefined symbol error.

Original issue following.

---- 

Hi,

I am trying to get the torchbeast agent to run in order to generate some trajectories I can initialize my own agents to. I installed torchbeast as per the README in the torchbeast repository (for polybeast). I was able to compile it, although I did have to make a modification to one of the dependencies (abseil-cpp) to fix an incompatibility with GCC 11 (missing limits header).

However, now when I try to run the baseline (nethack_baselines/torchbeast/polyhydra.py) I get the following:

```
python3 polyhydra.py 
Traceback (most recent call last):
  File "/home/.../neurips-2021-the-nethack-challenge/nethack_baselines/torchbeast/polyhydra.py", line 40, in <module>
    import polybeast_env
  File "/home/.../neurips-2021-the-nethack-challenge/nethack_baselines/torchbeast/polybeast_env.py", line 23, in <module>
    import libtorchbeast
  File "/usr/lib/python3.9/site-packages/libtorchbeast-0.0.20-py3.9-linux-x86_64.egg/libtorchbeast/__init__.py", line 18, in <module>
    from ._C import (
ImportError: /usr/lib/python3.9/site-packages/libtorchbeast-0.0.20-py3.9-linux-x86_64.egg/libtorchbeast/_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

Any ideas? I am using Python 3.9 on Manjaro Linux. Note that I do not have an Nvidia GPU and intend to run inference on the CPU.

**Comment by heiner** [comment]
Cross-posting reply:

Hey @CireNeikual,

Looking at https://demangler.com, the symbol it appears to fail to load is `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)`.

My guess is that this means the version of PyTorch on your machine is compiled with a compiler that's not compatible with the one you compiled TorchBeast with. This is a tricky issue that lots of Python packages that depend on PyTorch run into.

The issue stems from the `-D_GLIBCXX_USE_CXX11_ABI=1` setting applied to the PyTorch package when it was compiled. This can be checked via

```
import torch
import os
int(torch._C._GLIBCXX_USE_CXX11_ABI)
```

As for fixes, I don't know of anything better than for you to compile PyTorch from source.
