### ISSUE TITLE
[Challenge] Polyhydra Cmake Issue

### ISSUE THREAD

**Issue by drothermel** [facebookresearch/nle#204]
See original issue on the AICrowd Nethack Challenge repo [here](https://discourse.aicrowd.com/t/issue-while-installing-polybeast/6129/3)

Poster ran through the instructions in the torchbeast README as instructed and still ran into a `Unknown CMake command "pybind11_add_module"` issue.

**Comment by heiner** [comment]
Resolved after cloning all submodules.
