### ISSUE TITLE
Make statuses like 'Blind', 'Conf', 'Hallu', 'Slimed' available in BLStats

### ISSUE THREAD

**Issue by tanderson11** [facebookresearch/nle#215]
Certain character statuses in Nethack are made visible to the player on the bottom line such as hallucination, confusion, blindness, illness, being stunned. While these characters are legibile in the raw observation, they are not made available to the player via `nle` in the `BLStats` class. 

I think these statuses should be made available natively through `nle`. Playing Nethack in a terminal occasionally causes some of these statuses to be forced offscreen if the window is narrow or the player is suffering from many conditions. Personally, I would like to see this behavior be avoided and have the statuses made available regardless of window size or number of conditions, but I'd also be happy with other implementations as well.

**Comment by heiner** [comment]
This has happened in #219 and was released in version 0.7.3.
