### ISSUE TITLE
Log files accumulating

### ISSUE THREAD

**Issue by etaoxing** [facebookresearch/nle#239]
Had to compile from source to run on my machine, I'm on the 0.7.3 release commit. 

I'm getting a bunch of `nethack.Agent.{timestamp}.log` files accumulating in `/tmp`. How do I prevent these from getting generated? They're taking up space and not being deleted.

**Comment by heiner** [comment]
Hey e.xing,

Thanks for your interest in NLE.

I'm not aware that we currently produce log files of that kind. E.g., when I look inside this repository,

```
$ git grep '\.log' '*.py'
```

there seems to be no result along these lines. Could you elaborate what you are running when you encounter this issue?

**Comment by etaoxing** [comment]
I'm actually using the [MiniHack](https://github.com/MiniHackPlanet/MiniHack) task definitions, so running from their gym environments. I'm also running multiple environments in parallel, so seeing each env having `$HACKDIR` copied to its own subdirectories in `/tmp`, while these `nethack.*.logs` accumulate directly in `/tmp`.

I think these log files are being produced by:https://github.com/facebookresearch/nle/blob/f9b55a630831cce5be974dd2747e3efb985b1a40/include/ntconf.h#L30

Let me know if you need more info!

**Comment by heiner** [comment]
Hey e.xing,

Yes, you are right! We involuntarily enabled NetHack dumplogs when we simplified something else in  https://github.com/facebookresearch/nle/pull/210/commits/1c38269743df2f431b16ad733cbdb8b6a8515594.

Thanks for pointing this out. This should be fixed after https://github.com/facebookresearch/nle/pull/240.
