### ISSUE TITLE
Conda-only install (i.e. without requiring sudo)

### ISSUE THREAD

**Issue by SamNPowers** [facebookresearch/nle#246]
## 🚀 Feature

Users of the environment may not always have access to sudo; for instance, on my lab's clusters, I am mostly restricted to what I can conda-install. Thus a streamlined set of conda install instructions would make the environment accessible to more users.

## Pitch

Here is the set of installs that seems to work for me, tested on two very different setups (1 RedHat with old system libraries, and 1 new ubuntu machine with a very minimal set of pre-installed libraries):

1. conda install cmake flex bison bzip2
2. conda install -c conda-forge cxx-compiler
3. install all of the sysroot libraries here: https://github.com/conda-forge/linux-sysroot-feedstock (it seems unlikely they are all necessary, but I have only tested with all)
4. pip install nle

**Comment by heiner** [comment]
Thanks for figuring this out and taking the time to write it up!

**Comment by heiner** [comment]
Thanks again for the write-up. I'll close the issue now but will refer to it in case this comes up in the future.

**Comment by Hust1Booze** [comment]
Thank you very much ! i suffer for hours with this.

**Comment by cuicui2023** [comment]
How to operate the third step specifically?

**Comment by cuicui2023** [comment]
In the anaconda virtual environment, the first step of installing the flex and bison packages is not possible
