### ISSUE TITLE
Spawn start method results in NLE installation not found

### ISSUE THREAD

**Issue by SamNPowers** [facebookresearch/nle#248]
## 🐛 Bug

When NLE is run in parallel using the "spawn" start method, I'm observing issues with new environments finding the nethack installation.

On mac this bug results in:
```
FileNotFoundError: Couldn't find NetHack installation at '/var/folders/hm/qdpmt3cn1l15skz8rvh0c7nm0000gn/T/nlewd1m7m07'.
```

On Linux:
```
FileNotFoundError: Couldn't find NetHack installation at '/tmp/nlea01ws10x'.
```

## To Reproduce

```
import gym
import nle
import multiprocessing


def start_nethack(id):
    gym.make("NetHackScore-v0")
    return True


def main():
    start_nethack(None)  # Initializes HACKDIR to the temp folder, which will disappear when the env is cleaned up

    async_objs = []
    num_processes = 1
    with multiprocessing.Pool(processes=num_processes) as pool:
        for id in range(num_processes):
            async_objs.append(pool.apply_async(start_nethack, (id,)))

        for obj in async_objs:
            success = obj.get()


if __name__ == "__main__":
    multiprocessing.set_start_method("spawn")
    main()

```

## Expected behavior
No failure

## Environment

```
NLE version: 0.7.3+d10ee7a
PyTorch version: 1.9.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 11.5.2
GCC version: Could not collect
CMake version: version 3.19.6

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] pytorch-lightning==1.4.6
[pip3] torch==1.9.0
[pip3] torchmetrics==0.5.1
[pip3] torchvision==0.10.0
[conda] pytorch-lightning         1.4.6                    pypi_0    pypi
[conda] torch                     1.9.0                    pypi_0    pypi
[conda] torchmetrics              0.5.1                    pypi_0    pypi
[conda] torchvision               0.10.0                   pypi_0    pypi
```

## Possible fix

If you always get HACKDIR from the installed resource, rather than the environment variable, this issue ceases to occur:
```
# HACKDIR = os.getenv("HACKDIR", pkg_resources.resource_filename("nle", "nethackdir"))
HACKDIR = pkg_resources.resource_filename("nle", "nethackdir")
```

## Issues with fix (and possible different fix)

However, even if you make that change, but use a MiniHack environment instead, you get:
```
/Users/spowers/Git/minihack/minihack/scripts/mh_patch_nhdat.sh: line 19: /var/folders/hm/qdpmt3cn1l15skz8rvh0c7nm0000gn/T/nle_ogknj9d/lev_comp: No such file or directory
/Users/spowers/Git/minihack/minihack/scripts/mh_patch_nhdat.sh: line 22: /var/folders/hm/qdpmt3cn1l15skz8rvh0c7nm0000gn/T/nle_ogknj9d/dlb: No such file or directory
mv: nhdat: No such file or directory
```
I am not sure if this variable is being assigned by NLE or MiniHack (I haven't gotten a chance to dig in further). 

If instead of setting HACKDIR as mentioned above, you simply comment out `_set_env_vars(self._options, self._vardir)` in nethack.py, neither issue occurs, and all seems well.

**Comment by heiner** [comment]
Hey @SamNPowers, thanks for the bug report!

I discussed with @samvelyan, author of MiniHack, and he suggests your "Possible fix" should work for MiniHack too, and tried that out in https://github.com/facebookresearch/nle/pull/249#pullrequestreview-757362556.

I'm still surprised that NetHack is fine with not calling `_set_env_vars(self._options, self._vardir)`, as it will try to create files in that directory. I suspect that might not work for users who don't use conda and have no write access to the `pkg_resources.resource_filename` directory.

I'll therefore go ahead with the "possible fix". Thanks again for digging into this!
