### ISSUE TITLE
Allow plot script to take named column

### ISSUE THREAD

**Issue by dmadeka** [facebookresearch/nle#257]
Would it make sense to add an argument that sets the x column and y column for the plot (defaulting to the current values)?

Happy to open a PR here myself - just wanted to see if this was of interest

**Comment by heiner** [comment]
Hey, that's a good idea.

In fact, I tend to use a console plotting script along the lines of https://gist.github.com/heiner/c82cfef7cc368b02fd831595f3a1435f which does what I think you are proposing.

**Comment by heiner** [comment]
Please go ahead :)

**Comment by dmadeka** [comment]
Closed via #259
