### ISSUE TITLE
Does the permonst mlevel correspond to the Base Monster Level?

### ISSUE THREAD

**Issue by dmadeka** [facebookresearch/nle#258]
I was trying to create an Embedding Layer for the difficulty of the monster and figured Id ask here:

```python
In [1]: from nle.nethack import permonst                                                                                                                                                                           

In [2]: dispater, geryon = permonst(304), permonst(303)                                                                                                                                                            

In [3]: dispater.mname, dispater.mlevel                                                                                                                                                                            
Out[3]: ('Dispater', 78)

In [4]: geryon.mname, geryon.mlevel                                                                                                                                                                                
Out[4]: ('Geryon', 72)
```

What does mlevel in the permonst struct correspond to? The documentation seems to indicate it should be the [base monster level](https://github.com/facebookresearch/nle/blob/main/win/rl/pynethack.cc#L521). But that doesnt seem to align with the Nethack Wiki base levels for [Dispater](https://nethackwiki.com/wiki/Dispater) and [Geryon](https://nethackwiki.com/wiki/Geryon)?

**Comment by dmadeka** [comment]
Does look like the [NetHack Wiki is wrong](https://github.com/facebookresearch/nle/blob/main/src/monst.c#L2516)! Probably needs some updating for the max level -

**Comment by heiner** [comment]
The same issue (on a much worse scale) happens when trying to use glyph ids for embedding, see https://github.com/facebookresearch/nle/issues/21.
