### ISSUE TITLE
CTRL characters in action space

### ISSUE THREAD

**Issue by kolbytn** [facebookresearch/nle#281]
## 🚀 Feature

ctrl characters in the action space to allow full functionality of wizard mode

## Motivation

I was using scrolls and potions to identify objects and increase my character level, but then I realized I could be using wizard mode to do these. For example `ctrl-i`/`\t` will identify items and `#levelchange` will change a character's level (the latter requires the use of `crtl-j`/`\n`). I can enter into wizard mode, but I can only use the wizard commands that do not require ctrl characters.

## Alternatives

An alternative way to execute all wizard commands.

## Additional context

I'm using nle via minihack. 

Is there another way to do this that I am missing?

**Comment by heiner** [comment]
Closing as we added all available wizard actions. Please reopen if this is still an issue.
