### ISSUE TITLE
Update dashboard path 

### ISSUE THREAD

**Issue by blurry-mood** [facebookresearch/nle#284]
Hi,

I think you need to update the dashboard path from `NetHack/dash` to `nle/dashboard`  [here](https://github.com/facebookresearch/nle/tree/main/nle/dashboard#installation-and-usage).

**Comment by heiner** [comment]
Hey Ayoub,

Thanks for your interest in NLE. We've [just decided](https://github.com/facebookresearch/nle/pull/306) to remove the JavaScript dashboard as we haven't been maintaining it very well. (To bring it back to live one needs to write certain stat files which we don't currently do.)
