### ISSUE TITLE
ModuleNotFoundError: No module named 'nle.nethack.helper'

### ISSUE THREAD

**Issue by ben-heil** [facebookresearch/nle#30]
## To Reproduce

1. Install nethack on Ubuntu 18.04 LTS by following the instructions in the README
2. Install torchbeast agent according to instructions
3. Run `python -m nle.agent.agent --num_actors 80 --batch_size 32 --unroll_length 80 --learning_rate 0.0001 --entropy_cost 0.0001 --use_lstm --total_steps 1000000000`
4. Get the error below

``` python
Traceback (most recent call last):
  File "/home/heil/anaconda3/envs/nle/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/heil/anaconda3/envs/nle/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/heil/repos/nle/nle/__init__.py", line 4, in <module>
    import nle.env
  File "/home/heil/repos/nle/nle/env/__init__.py", line 4, in <module>
    from nle.env.base import NLE, DUNGEON_SHAPE, seed_list_to_dict
  File "/home/heil/repos/nle/nle/env/base.py", line 16, in <module>
    from nle import nethack
  File "/home/heil/repos/nle/nle/nethack/__init__.py", line 5, in <module>
    from nle.nethack.helper import *  # noqa: F403
ModuleNotFoundError: No module named 'nle.nethack.helper'
```

## Expected behavior

Expected behavior is that the agent would start running I suppose. I can get it to work by commenting out the import line in `nethack/__init__.py`, but I imagine that I'm breaking something that I haven't found yet.

## Environment

Please copy and paste the output from running our
[environment collection script](https://raw.githubusercontent.com/facebookresearch/nle/master/nle/scripts/collect_env.py)
(or fill out the checklist below manually).

NLE version: 0.1.1+517c6b5
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 440.82
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.0

Versions of relevant libraries:
[pip] numpy==1.18.4
[pip] numpysane==0.22
[pip] torch==1.5.0
[conda] torch                     1.5.0                    pypi_0    pypi

**Comment by edran** [comment]
Hi @ben-heil,

it looks like you are using the repo locally. Can you try running `pip install -e .` and then retrying?

**Comment by ben-heil** [comment]
That fixed it, thanks!
