### ISSUE TITLE
About fully-observed MDP

### ISSUE THREAD

**Issue by albertcity** [facebookresearch/nle#313]
Hi,
I find that the observations in all tasks are partially-observed (i.e. some information is hidden from the agent's view). Does there exist any interface to make the observations fully observed?
Tks a lot for any help :)

**Comment by condnsdmatters** [comment]
Hi there,

I'm very sorry but the whole of NetHack state is implicity partially observed!  No such task I think has a full observed state. Even if you restrict the game to one level and use all the observation keys, including inventory, there are still many hidden states in the game that may affect how game play develops (eg [Luck](https://nethackwiki.com/wiki/Luck) ).
