### ISSUE TITLE
NLE crashing when run on WSL

### ISSUE THREAD

**Issue by russellw** [facebookresearch/nle#331]
## 🐛 Bug

NLE on WSL successfully installs, but crashes when I try to run it.

## To Reproduce

1. Follow the steps in the Readme, under the heading "On a plain Ubuntu 18.04 distribution."
2. `python -m nle.scripts.play`

```
	(nle) a@DESKTOP-4B7M920:~$ python -m nle.scripts.play
	/home/a/anaconda3/envs/nle/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:97: UserWarning: WARN: We recommend you to use a symmetric and normalized Box action space (range=[-1, 1]) https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html
	  logger.warn(
	/home/a/anaconda3/envs/nle/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:216: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
	  logger.warn(
	/home/a/anaconda3/envs/nle/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:228: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed `return_info` to return information from the environment resetting.
	  logger.warn(
	/home/a/anaconda3/envs/nle/lib/python3.8/site-packages/gym/utils/passive_env_checker.py:233: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
	  logger.warn(
	--------
	Previous reward: 0.0
	Previous action:
	--------
	Traceback (most recent call last):
	  File "/home/a/anaconda3/envs/nle/lib/python3.8/runpy.py", line 194, in _run_module_as_main
		return _run_code(code, main_globals, None,
	  File "/home/a/anaconda3/envs/nle/lib/python3.8/runpy.py", line 87, in _run_code
		exec(code, run_globals)
	  File "/home/a/anaconda3/envs/nle/lib/python3.8/site-packages/nle/scripts/play.py", line 280, in <module>
		main()
	  File "/home/a/anaconda3/envs/nle/lib/python3.8/site-packages/nle/scripts/play.py", line 276, in main
		play()
	  File "/home/a/anaconda3/envs/nle/lib/python3.8/site-packages/nle/scripts/play.py", line 119, in play
		env.render(FLAGS.render_mode)
	TypeError: render() takes 1 positional argument but 2 were given
```

The above was the output on the first attempt. I noticed in another issue report, a remark to the effect that gym 0.24 has become stricter, so I tried downgrading it to 0.23 and rerunning NLE. Now it crashes with a different error:

	(nle) a@DESKTOP-4B7M920:~/nle$ python -m nle.scripts.play
	Traceback (most recent call last):
	  File "/home/a/anaconda3/envs/nle/lib/python3.8/runpy.py", line 185, in _run_module_as_main
		mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
	  File "/home/a/anaconda3/envs/nle/lib/python3.8/runpy.py", line 111, in _get_module_details
		__import__(pkg_name)
	  File "/home/a/nle/nle/__init__.py", line 4, in <module>
		import nle.env
	  File "/home/a/nle/nle/env/__init__.py", line 5, in <module>
		from nle.env.base import NLE, DUNGEON_SHAPE
	  File "/home/a/nle/nle/env/base.py", line 15, in <module>
		from nle import nethack
	  File "/home/a/nle/nle/nethack/__init__.py", line 3, in <module>
		from nle._pynethack.nethack import *  # noqa: F403
	ModuleNotFoundError: No module named 'nle._pynethack'

## Expected behavior

Play NetHackStaircase-v0 as a human. I also tried the command to run it in random mode, with similar results.

## Environment

```
(nle) a@DESKTOP-4B7M920:~/nle$ python collect_env.py
Collecting environment information...
NLE version: N/A
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.23.2

Python version: 3.8
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.23.1
[conda] Could not collect
```

**Comment by condnsdmatters** [comment]
Hi @russellw, is this still an issue. It looks like NLE never properly installed.

**Comment by condnsdmatters** [comment]
Closing, feel free to reopen if the issue rears its head again.
