### ISSUE TITLE
Understanding the observation space

### ISSUE THREAD

**Issue by xvzrli** [facebookresearch/nle#35]
Hi. I'm not sure I fully understand the observation space of this environment.
```
>>> env.observation_space
Dict(glyphs:Box(21, 79), inventory:Tuple(Box(55,), Box(55, 80), Box(55,), Box(55,)), 
     message:Box(256,), status:Box(23,))
```
Is there any documentation? For instance, where are the raw "pixels" located? E.g. where is this:

```
                           --------                                            
                           |d.....|                                            
                           +@$....|                                            
                           |.......                                            
                           ------ -    
```
encoded? In glyphs? I think so, because in [1]:
```     self.glyph_shape = observation_shape["glyphs"].shape
        self.status_size = observation_shape["status"].shape[0]

        self.num_actions = num_actions
        self.use_lstm = use_lstm

        self.H = self.glyph_shape[0]
        self.W = self.glyph_shape[1]
```
It seems that it is used as a 2D matrix/image.

I understand that the field "message" corresponds to a byte string such as `b'Hello Agent9, welcome to NetHack!  You are a neutral male human Monk.'`, no mystery there.

Any hints on how is `inventory` exactly encoded?

Finally, by looking at the code I understand that the agent provided in the module [1] does't use the inventory and the message, only glyphs and status. Is that right? Are the other fields in the observation space supposed to be used but you didn't because it's just a baseline, or are there other reasons why you aren't using them? Would it make sense that I tried to use the message?

Many thanks.

[1] `NetHackNet` in <https://github.com/facebookresearch/nle/blob/master/nle/agent/agent.py>

**Comment by heiner** [comment]
Hey xvzrli,

Thanks for your interest in NLE; these are great questions. We'll soon have a whitepaper that describes this in more detail, but for now here's some info:

> The Gym environment is implemented by wrapping a more low-level NetHack Python object into a Python class responsible for the featurization, reward schedule and end-of-episode dynamics. While the low-level NetHack object exposes a large number of NetHack game internals, the Gym wrapper exposes by default only a part of this data as numerical observation arrays, namely the tuple
> (glyphs, stats, message, inventory).
> Glyphs: NetHack supports non-ASCII graphical user interfaces, dubbed window-ports. To support displaying different monsters, objects and floor types in the NetHack dungeon
> map as different tiles, NetHack internally defines glyphs as ids in the range 0, . . . , MAX_GLYPH, where
> MAX_GLYPH = 5991 in our build. The glyph observation is an integer array of shape (21, 79) of these Stats: A integer vector of length 23, containing the (x, y) coordinate of the hero and the following 21 character stats: StrengthPercentage, Strength, Dexterity, Constitution, Intelligence, Wisdom, Charisma, Score, Hitpoints, MaxHitpoints, Depth, Gold, Energy, MaxEnergy, ArmorClass, MonsterLevel, ExperienceLevel, ExperiencePoints, Time, HungerLevel, CarryingCapacity.
> Message: A padded byte vector of length 256 representing the current message shown to the player, normally displayed in the top area of the GUI. We support different padding strategies and alphabet sizes, but by default we choose an alphabet size of 96, where the last character is used for padding.
> Inventory: In NetHack’s default ASCII user interface, the hero’s inventory can be opened and closed during the game. Other user interfaces display a permanent inventory at all times. NLE follows that strategy. The inventory = (glyphs, strs, letters, oclass) observation is a tuple of the following four arrays: glyphs: an integer vector of length 55 of glyph ids, padded with MAX_GLYPH; strs: A padded byte array of shape (55, 80) describing the inventory items; letters: A padded byte vector of length 55 with the corresponding ASCII character symbol; oclass: An integer vector of shape 55 with ids describing the type of inventory objects, padded with MAXOCLASSES = 18.
> The low-level NetHack Python object has additional entries for the dungeon map’s character symbols and colors as well as various parts of the program state of the underlying NetHack process, including the contents of all in-game windows (e.g., menus and other pop-ups). We refer to the source code to describe these.

You can see the definitions of these at e.g. https://github.com/facebookresearch/nle/blob/master/nle/env/base.py#L142

As an aside, NetHack's set of glyph ids is not necessarily well suited for machine learning. For example, more than half of all glyph ids are of type ``swallow'', most of which are guaranteed not to show up in any actual game of NetHack. See #21 for details.

As for your final question: Yes, this agent is just a baseline agent and using the messages would presumably be helpful :)

**Comment by heiner** [comment]
That said, there's also character/color information if you'd prefer that, but it's currently a little bit more hidden. The code at https://github.com/facebookresearch/nle/blob/master/nle/nethack/print_message.py#L171 (used, among other places, in play.py) shows how to use that.

**Comment by xvzrli** [comment]
@heiner Hi! Many thanks for your answers! I'm looking forward to that whitepaper.

**Comment by heiner** [comment]
Whitepaper is now released: https://arxiv.org/abs/2006.13760
