### ISSUE TITLE
please allow us to prefix 'nle_data' folder

### ISSUE THREAD

**Issue by bionicles** [facebookresearch/nle#44]
## 🚀 Feature

dir_prefix='/path/to/nle_data'

## Motivation

the nle_data folder stuff in base.py works great, but it puts the nle data in the root of my project, which isn't where I'd like to keep that folder. If I specify the path, then it doesn't do all the same stuff, and crashes with a FileExistsError, so I'd have to manually generate paths for each game, which is annoying

## Pitch

if savedir is not None, then just put it before 'nle_data'

exact part of the code that crashes for me if i incorrectly specify savedir:
https://github.com/facebookresearch/nle/blob/a5a7207cb398d85f598727a9c8f1c7b63bae583a/nle/env/base.py#L331

current code:
```py
if savedir is None:
    parent_dir = os.path.join(os.getcwd(), "nle_data")
    os.makedirs(parent_dir, exist_ok=True)
    # Create a unique subdirectory for us.
    self.savedir = tempfile.mkdtemp(
        prefix=time.strftime("%Y%m%d-%H%M%S_"), dir=parent_dir
    )
else:
    self.savedir = savedir
    os.makedirs(self.savedir)
```
desired change:
```py
savedir = os.getcwd() if savedir is None else savedir
parent_dir = os.path.join(savedir, "nle_data")
os.makedirs(parent_dir, exist_ok=True)
# Create a unique subdirectory for us.
self.savedir = tempfile.mkdtemp(
    prefix=time.strftime("%Y%m%d-%H%M%S_"), dir=parent_dir
)
```

## Alternatives

I could copy paste your code to autogenerate unique subdirectories

## Additional context

Thanks for making NLE

**Comment by heiner** [comment]
Hey! Thanks for using NLE and taking the time to give feedback.

I'm not sure I like this suggestion as-is though; it would create a new "ugly" savedir subdirectory in the user-supplied savedir.

Can you elaborate what FileExistsError you run into?

**Comment by bionicles** [comment]
here's the error -- I just wanted to put something like ./nurture/nle/data instead of ./nle_data 
```
ERROR    root:nethack.py:163 Archive file nurture/nle/data/nethack.%(pid)i.%(time)s.zip exists, terminating
Traceback (most recent call last):
  File "/home/bion/miniconda3/lib/python3.7/site-packages/nle/nethack/nethack.py", line 160, in __init__
    "x",
  File "/home/bion/miniconda3/lib/python3.7/zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
FileExistsError: [Errno 17] File exists: 'nurture/nle/data/nethack.1056.20200702-125740.zip'
```

**Comment by bionicles** [comment]
what about this
```py
if savedir is None:
     parent_dir = os.path.join(os.getcwd(), "nle_data")
else:
     parent_dir = os.path.join(os.get_cwd(), savedir)
```
open to suggestions -- I just want to add a prefix to nle_data so i can put it into the subdirectory i have for task/env data

**Comment by heiner** [comment]
That won't work for our usecase -- when we sent things off to our cluster we want to be sure the data ends up where we tell it to, not somewhere inside `cwd`.

But what I don't understand and where I'd like to fix this is why you see this error about `nurture/nle/data/nethack.1056.20200702-125740.zip` existing -- why would that file exist already?

**Comment by bionicles** [comment]
it might be because i'm testing the envs in a loop


nurture/names.py
```
NETHACK = ['NetHack-v0','NetHackScore-v0','NetHackStaircase-v0','NetHackStaircasePet-v0','NetHackOracle-v0','NetHackGold-v0','NetHackEat-v0','NetHackScout-v0']

NAME_LISTS = {
    'nethack': NETHACK,
    ...
}

def yield_names():
    for name_list in NAME_LISTS.values():
        yield from name_list
```

tests/nurture/test_envs.py
```
from nurture import yield_names, make_env
from tqdm import tqdm

def check_env(name):
    env = make_env(name)
    o = env.reset()
    o,r,d,i = env.step(env.action_space.sample())
    try:
        env.render()
    except Exception as e:
        print(name, 'doesnt implement render   <-----')
    env.close()

def test_envs():
    [check_env(name) for name in tqdm(list(yield_names()))]
```
It's potentially just testing the next env so fast it winds up using the same exact filename
One solution to that might be to include the task name in the filename, in addition to the timestamp

**Comment by bionicles** [comment]
what i really meant to ask was, could we pass an argument for 'parent_dir' -- so it keeps making the temporary savedirs in a different parent directory

**Comment by heiner** [comment]
This could be done just by doing a `os.chdir` before creating the next one -- or by supplying it with a different `archivefile` setting every time.

But I am still surprised you're seeing this:
> But what I don't understand and where I'd like to fix this is why you see this error about nurture/nle/data/nethack.1056.20200702-125740.zip existing -- why would that file exist already?

Note that the default archivefile pattern includes the process id, and I doubt you're creating two processes with the same id in the same second.

**Comment by edran** [comment]
Hi @bionicles -- following up on this; are you still experiencing the `FileExistsError` issue?

**Comment by bionicles** [comment]
dunno, been working on "nature" side of nature/nurture, it was working if I just let it put the nle folder in the root of my directory

**Comment by bionicles** [comment]
the FileExistsError was happening because my test suite was running in parallel mode https://pypi.org/project/pytest-xdist/

**Comment by edran** [comment]
>the FileExistsError was happening because my test suite ran in parallel mode pypi.org/project/pytest-xdist i think

Thank you for following up on this. I'm still confused by this issue, as I have used xdist in the past to run our tests and found it to be working (furthermore, it shouldn't blow up this way, if anything).

I'm going to close this issue for now, and will reopen it if it ends up being relevant again.
