### ISSUE TITLE
Implementation of RND as baseline

### ISSUE THREAD

**Issue by dzorlu** [facebookresearch/nle#48]
## 🚀 Feature

Hi- Thank you very much for this great & challenging environment. Looking forward to working on this.
The paper reports that the addition of RND improves the baseline performance across many tasks, but to me it looks like the implementation is missing in the codebase. Is this something you are planning to release? 

I'd be happy to work on it as well, though I have limited exposure :)

**Comment by heiner** [comment]
Hey, thanks for the kind words!

The baseline agent we've released isn't what we report in the paper. The implementation for the paper is more ... messy, and based on PolyBeast. We're still experimenting with that and may be open sourcing this one in the future.

However, you can find a decent introduction to RND at https://medium.com/data-from-the-trenches/curiosity-driven-learning-through-random-network-distillation-488ffd8e5938, which is hopefully enough to get you started. Note though that I/we haven't tested if the baseline agent in this repo achieves the same performance as our results in the paper. The baseline agent here is just for illustration purposes.

We may update TorchBeast and this agent at a later stage.

**Comment by dzorlu** [comment]
Understood. Thank you for your quick response!

**Comment by rockt** [comment]
Hi, you might also want to have a look at the RND implementation used for the [RIDE paper](https://arxiv.org/abs/2002.12292):
 https://github.com/facebookresearch/impact-driven-exploration/blob/master/src/algos/rnd.py
