### ISSUE TITLE
Default env rendering needs some improvements

### ISSUE THREAD

**Issue by edran** [facebookresearch/nle#5]
`NLE().render()` is currently really basic, and quite unpleasant to use when testing a batch of envs at the same time, due to mixed output and all sort of subpar UX.

We should do the following:
- [ ] Render to a separate terminal window (that is spawned with the first `env.render()`, and is locked to that particular instance of the environment). Focusing on ease to use and speed.
- [x] Render the inventory and items such that the information is well structured and readable.
- [ ] Build an API to modify this rendering behaviour, such that downstream tasks can modify the rendering process to add particular features.

Tagging this as `good first issue` since it's a relatively well-contained task, and can be broken down into subtasks fairly easily.

We will also most likely deal with this ourselves in the next few weeks, but putting this down here just in case someone finds time & capacity to do it earlier. Note that this involves some quite important design decisions, so we might be fairly strict in accepting patches.

**Comment by prematurelyoptimized** [comment]
I would add as a request to do something smarter than just a list of print statements as the naive approach to animating a rollout:
```while condition:
   env.render(some_action)
```
leads to the terminal scrolling, making it hard to track state changes from step to step.

**Comment by rockt** [comment]
Switched to tty rendering.
