### ISSUE TITLE
Trouble installing Nethack in conda environment

### ISSUE THREAD

**Issue by jrieffel** [facebookresearch/nle#6]
## 🐛 Bug

Following the steps in the Readme, I created a new nle conda environment, installed flatbuffers and zeromq, and then `pip install nle`, however this error occurs during the build.

I suspect it is failing to find the flatbuffers libraries?

## To Reproduce

```
$ conda create -n nle python=3.7
$ conda activate nle
$ conda install zeromq flatbuffers
$ pip install nle
```

```
./mkmkfile.sh: 43: ./mkmkfile.sh: cannot create ../../doc/Makefile: Directory nonexistent
    Generated NetHack makefiles with hints/linux.
    ( cd src ; make )
    make[1]: Entering directory '/tmp/pip-build-2ug4vby6/nle/src'
    flatc -o ../win/rl --cpp --python ../win/rl/message.fbs
    g++ -g -O -I../include -DNOTPARMDECL -DDLB -DCOMPRESS=\"/bin/gzip\" -DCOMPRESS_EXTENSION=\".gz\" -DSYSCF -DSYSCF_FILE=\"/usr/lib/games/nethack/sysconf\" -DSECURE -DTIMED_DELAY -DHACKDIR=\"/usr/lib/games/nethack\" -DCONFIG_ERROR_SECURE=FALSE -DCURSES_GRAPHICS -fPIC -I. -c ../win/rl/winrl.cc
    In file included from /usr/include/c++/5/array:35:0,
                     from ../win/rl/winrl.cc:2:
    /usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
     #error This file requires compiler and library support \
      ^
    In file included from ../win/rl/winrl.cc:11:0:
    ../win/rl/message_generated.h:7:37: fatal error: flatbuffers/flatbuffers.h: No such file or directory
    compilation terminated.
    Makefile:1062: recipe for target 'winrl.o' failed
    make[1]: *** [winrl.o] Error 1
    make[1]: Leaving directory '/tmp/pip-build-2ug4vby6/nle/src'
    Makefile:169: recipe for target 'nethack' failed
    make: *** [nethack] Error 2
    Failed to build NetHack
```
## Expected behavior

expected a clean install

## Environment

```
Collecting environment information...
NLE version: N/A
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro K1200
Nvidia driver version: 384.130
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.3.1
[pip3] torchvision==0.4.2
[conda] Could not collect
```

## Additional context

Edit(@edran): formatting

**Comment by edran** [comment]
Hi, thank you for trying it out!

I believe it's likely you will need to install flatbuffers (i.e. `make` + `make install`, either on source or through pre-built packages) in some way. The conda package might not be enough to pull the relevant dependencies (and we should update the README to reflect that).

I'm building a Dockerfile that documents how to install all the dependencies on Ubuntu 18.04, please have a look at it and check whether this can work you: https://github.com/facebookresearch/nle/blob/fda22ea27b07a1c80d1a41df21e02f64426c85ab/docker/Dockerfile

**Comment by jrieffel** [comment]
Progress:  installed flashbuffers as directed, now getting a new error building nethack.  I suspect having to do with the makefile for nethack?
 
See attached error log

[errorlog.txt](https://github.com/facebookresearch/nle/files/4587950/errorlog.txt)

**Comment by edran** [comment]
I think there are multiple issues here (compiler used & its version), as well as some puzzling issues with building the wheel that I haven't seen before. Tomorrow I'll try installing nle on a clean Ubuntu 16.04 and will get back to you, but in the meanwhile I would suggest just using the docker image.

**Comment by jrieffel** [comment]
thanks appreciate it!

**Comment by edran** [comment]
Okay, I can reproduce your (main) issue in a clean docker image. It indeed has to do with the default version of `g++`. I'll investigate if there is a clean fix, but the easiest way to progress for you is to update your build toolchain. This sometimes is not quite trivial with Ubuntu distros, so do so with care.

**Comment by edran** [comment]
Errata corrige: probably the easiest path forward would be the following (while we work out a patch + new release):

```
$ git clone -b v0.1.0 git@github.com:facebookresearch/nle
$ cd nle
$ vim sys/unix/hints/linux  # or use emacs / any other editor
# now edit L44 with `CXXFLAGS= -std=c++14 $(CFLAGS) -I.`, and save
$ pip install .  # or `pip install -e .` if you want to use the repo files
```

**Comment by jrieffel** [comment]
succeeded, although I needed to tell sudo the path to conda's python3 pip.
