### ISSUE TITLE
Latest version (6e35e02)'s demo TorchBeast agent crashes on startup

### ISSUE THREAD

**Issue by justinglibert** [facebookresearch/nle#65]
## 🐛 Bug

Latest version (6e35e02)'s demo TorchBeast agent crashes on startup

## To Reproduce
- Clone the commit with SHA:6e35e02 (latest when I submitted this issue)
- pip install -e ".[dev]"
- python -m nle.agent.agent --num_actors 80 --batch_size 32 --unroll_length 80 --learning_rate 0.0001 --entropy_cost 0.0001 --use_lstm --total_steps 100000000

## Expected behaviour

Not crash when it starts

## Observed behaviour

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/thesis/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/anaconda3/envs/thesis/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/thesis/nle/nle/agent/agent.py", line 960, in <module>
    main(flags)
  File "/home/ubuntu/thesis/nle/nle/agent/agent.py", line 953, in main
    train(flags)
  File "/home/ubuntu/thesis/nle/nle/agent/agent.py", line 437, in train
    env = create_env(flags.env, archivefile=None)
  File "/home/ubuntu/thesis/nle/nle/agent/agent.py", line 142, in create_env
    return gym.make(name, observation_keys=("glyphs", "status"), *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/thesis/lib/python3.8/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/ubuntu/anaconda3/envs/thesis/lib/python3.8/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/ubuntu/anaconda3/envs/thesis/lib/python3.8/site-packages/gym/envs/registration.py", line 60, in make
    env = cls(**_kwargs)
  File "/home/ubuntu/thesis/nle/nle/env/tasks.py", line 54, in __init__
    super().__init__(*args, actions=actions, **kwargs)
  File "/home/ubuntu/thesis/nle/nle/env/base.py", line 202, in __init__
    self.env = nethack.Nethack(
  File "/home/ubuntu/thesis/nle/nle/nethack/nethack.py", line 112, in __init__
    raise ValueError("Unknown observation '%s'" % key)
ValueError: Unknown observation 'status'

## Environment

NLE version: 0.5.0+6e35e02
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.5 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.17.3

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB

Nvidia driver version: 450.51.06
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.2
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.2
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.2
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.2
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.2
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.2
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.2

Versions of relevant libraries:
[pip3] libtorchbeast==0.0.14
[pip3] numpy==1.19.2
[pip3] numpysane==0.25
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl
[conda] libtorchbeast             0.0.14                   pypi_0    pypi
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.1.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] pytorch                   1.6.0           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchvision               0.7.0                py38_cu102    pytorch

## Additional context

None

**Comment by heiner** [comment]
Ah yes I forgot to update the example agent. The status observation is called `blstats` now.

Thanks for the report; will fix this asap.

**Comment by heiner** [comment]
Should be fixed now. Thanks again for pointing this out.
