### ISSUE TITLE
Segmentation fault with access to all actions

### ISSUE THREAD

**Issue by yobibyte** [facebookresearch/nle#86]
## 🐛 Bug

Segmentation fault when giving access to all actions. I suspect that this is because of the PREVMSG action.

## To Reproduce

```
from nle.env.tasks import NetHackScore
from nle.env.base import FULL_ACTIONS
from nle import nethack

available_actions = list(FULL_ACTIONS)
available_actions.remove(nethack.Command.EXTCMD)

env = NetHackScore(actions=available_actions)
env.seed(2312374182401459200, 619989031601008828)
env.reset()
for a_idx in range(0, len(env._actions)):
    print("executing", a_idx, env._actions[a_idx])
    obs, rew, done, _ = env.step(a_idx)
    print(obs['message'].tobytes().decode('utf-8'))
    if done:
        break
```

## Output

```
...
executing 60 Command.PRAY
There is a gnome corpse here; eat it? [ynq] (n) 
executing 61 Command.PREVMSG
There is a gnome corpse here; eat it? [ynq] (n) 
executing 62 Command.PUTON
zsh: segmentation fault  python test.py
```

## Environment

Collecting environment information...
NLE version: 0.5.1+be86593
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.6
GCC version: Could not collect
CMake version: version 3.18.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] libtorchbeast==0.0.14
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl  
[conda] libtorchbeast             0.0.14                   pypi_0    pypi
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py37hfbe908c_0  
[conda] mkl_fft                   1.1.0            py37hc64f4ea_0  
[conda] mkl_random                1.1.1            py37h959d312_0  
[conda] pytorch                   1.6.0                   py3.7_0    pytorch
[conda] torchvision               0.7.0                  py37_cpu    pytorch

**Comment by condnsdmatters** [comment]
Hey @yobibyte , Is this still a problem? I couldn't replicate the issue as above off master (though the about `EXTCMD` line seems to now be irrelevant)

**Comment by yobibyte** [comment]
I don't know. One reason that you can't replicate it could be because EXTCMD is not in the RL_ACTIONS anymore, @heiner removed it from there a while ago.

**Comment by heiner** [comment]
Closing for now, please reopen if this re-materializes.
